### ISSUE TITLE
Cannot change subheadline color in Storytelling component with `style` prop

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1380]
I want to change the subheadline color of the storytelling component by passing `style={{"--c-headline_subheadline--color": myCustomSubheadlineColor}}` to the storytelling component.

This doesn't work, because `--c-headline_subheadline--color` is overwritten by the headline component itself.

## Temporary workaround

Overwrite the subheadline style in css:

```css
.c-storytelling .c-headline__subheadline {
  color: var(--my-subheadline-color, var(--c-headline_subheadline--color));
}
```

Then `style={{"--my-subheadline-color": myCustomSubheadlineColor}}` on the storytelling component will change the color as desired.

Thanks @edridiger for filing this issue.
